### PR TITLE
fix: change localhost for production url and head content mod

### PR DESCRIPTION
**Pull request by ekbalam11**
Now the swagger config has the production URL therefore the view /docs should be working as expected. 

By the other hand, I realized the api has swagger in its meta description in the head file (image attached). I also changed the head file since it had a content text more accurate to the api's purpose. 

image

### CODE REVIEW

**Comment by omiras** [comment]
Hi @ekbalam11 

It's my bad I noticed the swagger request is made from client side.
It may look like it works now because we are requesting to codequestapi URL in production, but this may change in the future.

Please have a try on this and check if this works in localhost. If it does, it is likely to work also in production.

If you want to always use the current protocol and URL (`window.location.protocol` and `window.location.href`) to dynamically build the route to the API documentation, you can construct the URL as follows:

### Example:
```html
<script>
  // Get the current protocol (http: or https:)
  const currentProtocol = window.location.protocol;

  // Get the current base URL (without the path)
  const currentHost = window.location.hostname;
  const currentPort = window.location.port ? `:${window.location.port}` : ''; // Handle case where no port is specified

  // Build the base URL of the API documentation
  const apiBaseUrl = `${currentProtocol}//${currentHost}${currentPort}/api/v1/test-swagger`;

  console.log(apiBaseUrl); // For testing, log the result
</script>
```

### Explanation:
- **`window.location.protocol`**: Retrieves the protocol (either `http:` or `https:`).
- **`window.location.hostname`**: Retrieves the domain or IP address without the protocol (`localhost`, `codequestapi.onrender.com`, etc.).
- **`window.location.port`**: Retrieves the port number (if any). For example, `3000` for local development. If no port is specified, an empty string is used.
  
This will always dynamically generate the correct URL for the API documentation based on the current protocol, domain, and port (if specified). So, no matter whether you're using `localhost` or a live server (like `onrender.com`), the script will adjust the URL accordingly.

**Comment by ekbalam11** [comment]
ok, let me try. Also, do you think it would be a good practice to change the script inside the docs view file to the config carpet? We already have a swagger.config.js file that is actually useless. I can use it to insert the script there.

**Comment by ekbalam11** [comment]
Hello again. I have config the URL to be dynamic and now is working in localhost. Let me know if this would be enough. Thanks!

**Review by omiras — APPROVED** [review]
I changed the port and it still worked so it looks fine to me! Hit the MERGE button. 

image

**Pull request merged**
