### PR TITLE
Feature/17 newsletters

### PR DESCRIPTION
**Pull request by kevmhughes**

### CODE REVIEW

**Comment by kevmhughes** [comment]
This pull request integrates the newsletter functionality into the main branch. The changes include:

- Added necessary dependencies to `package.json` for newsletter functionality: mailchimp, node-cron, and nodemailer.
- Added two new routes in `index.routes.js`.
- Created `email.template.js` for email template management.
- Created `email.services.js` to encapsulate the logic for handling the newsletter functionality.
- Updated `env.example `with examples of required environment variables.
- Removed unused variable declarations.
- Added temporary basic html form on `home.ejs` to test `/subscribe` endpoint.

No merge conflicts were encountered.

**Review by kevmhughes — COMMENTED** [review]
No merge conflicts were encountered.

**Comment by MariaChmielinska** [comment]
Review: 
emailing function was tested. result: emails received
subscribe function as well. result: subscribed and unsubscribed successfully.

**Review by MariaChmielinska — APPROVED** [review]
Review:
emailing function was tested. result: emails received
subscribe function as well. result: subscribed and unsubscribed successfully.

**Pull request merged**
